import Footer from "../components/footer";
import Navigation from "../components/navigation";
import "../styles/global.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const firacode_light = localFont({
  src: "../public/fonts/FiraCode-Light.ttf",
  display: "swap",
  weight: "100 900",
  variable: "--font-firacode-light",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${firacode_light.className} border-[0.5px] border-[#607B96] h-screen text-[14px]`}
      >
        <Navigation />
        <div className="h-[calc(90vh-1px)]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
